/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DAObd;
/**
 *
 * @author Iagod
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConexaoBD {
    private static final String URL = "jdbc:mysql://localhost:3307/space_ijp?useSSL=false&serverTimezone=UTC";
    private static final String USER = "root";
    private static final String PASS = "1234";

    static {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // driver do Connector/J 8.x
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASS);
    }
    public static PreparedStatement getPreparedStatement(String sql) throws SQLException {
        return getConnection().prepareStatement(sql);
    }

    static PreparedStatement getPreparableStatement(String mysql) throws SQLException{
        return getConnection().prepareStatement(mysql);
    }
    public static PreparedStatement getPreparedStatement(String sql, int autoGeneratedKeys) throws SQLException {
    return getConnection().prepareStatement(sql, autoGeneratedKeys);
    }
    
}
