/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import Script.CargoDAO;
import Script.CargoJA;
import javax.swing.JOptionPane;

/**
 *
 * @author Iagod
 */
public class CargoJanela extends javax.swing.JFrame {

    private CargoDAO CargoDao = new CargoDAO();
    List<CargoJA> listaCargos = CargoDao.getLista();

    private boolean emEdicao = false;
    private boolean criando = false;

    public CargoJanela() {
        initComponents();
    }

    CargoJanela(Main aThis, boolean b) {
        initComponents();
        carregarTabelaCargos();
        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        inputCodigo.setEnabled(false);
        inputNome.setEnabled(false);
        inputSalarioInitial.setEnabled(false);
    }

    private void carregarTabelaCargos() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCargo.getModel();
        modelo.setRowCount(0);
        for (CargoJA c : listaCargos) {
            modelo.addRow(new Object[]{
                c.getCodCargo(),
                c.getNomeCargo(),
                c.getSalarioInicial()
            });
        }
    }

    private void trataEdicao(boolean status){
    inputNome.setEnabled(status);
    inputSalarioInitial.setEnabled(status);

    salvar.setEnabled(status);
    cancelar.setEnabled(status);
    cadastrar.setEnabled(!status);
    editar.setEnabled(!status);
    remover.setEnabled(!status);
    atualizar.setEnabled(!status);
}

    public boolean validaCampos() {
        if (inputNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do Cargo");
            inputNome.requestFocus();
            return false;
        }
        if (inputSalarioInitial.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o Salario inicial do Cargo");
            inputSalarioInitial.requestFocus();
            return false;
        }
        return true;
    }

    private int gerarCodigoDisponivel() {
        int codigo = 1;
        while (true) {
            boolean existe = false;
            for (CargoJA f : listaCargos) {
                if (f.getCodCargo() == codigo) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                return codigo;
            }
            codigo++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadastrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCargo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputSalarioInitial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Foguetes");

        jPanel1.setBackground(new java.awt.Color(149, 156, 182));

        cadastrar.setBackground(new java.awt.Color(37, 99, 235));
        cadastrar.setText("Criar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        editar.setBackground(new java.awt.Color(5, 150, 105));
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        remover.setBackground(new java.awt.Color(220, 38, 38));
        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        atualizar.setBackground(new java.awt.Color(245, 158, 11));
        atualizar.setText("Altualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        tabelaCargo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Salario Inicial"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCargo);
        if (tabelaCargo.getColumnModel().getColumnCount() > 0) {
            tabelaCargo.getColumnModel().getColumn(0).setResizable(false);
            tabelaCargo.getColumnModel().getColumn(1).setResizable(false);
            tabelaCargo.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        inputCodigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        cancelar.setBackground(new java.awt.Color(255, 0, 51));
        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salvar.setBackground(new java.awt.Color(51, 204, 0));
        salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Salario Inicial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputSalarioInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(inputSalarioInitial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
    CargoJA c = new CargoJA();
    c.setCodCargo(0);

    listaCargos.add(c);
    carregarTabelaCargos();

    int linha = listaCargos.size() - 1;
    if (linha >= 0) tabelaCargo.setRowSelectionInterval(linha, linha);

    inputCodigo.setText("0");
    inputNome.setText("");
    inputSalarioInitial.setText("");

    criando = true;
    emEdicao = true;
    trataEdicao(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
    int linha = tabelaCargo.getSelectedRow();
    if (linha < 0) {
        JOptionPane.showMessageDialog(this, "Selecione um Cargo para editar!");
        return;
    }
    CargoJA c = listaCargos.get(linha);
    inputCodigo.setText(String.valueOf(c.getCodCargo()));
    inputNome.setText(c.getNomeCargo());
    inputSalarioInitial.setText(String.valueOf(c.getSalarioInicial()));

    criando = false;
    emEdicao = true;
    trataEdicao(true);
    }//GEN-LAST:event_editarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
    int linha = tabelaCargo.getSelectedRow();
    if (linha < 0) {
        JOptionPane.showMessageDialog(this, "Selecione um Cargo para deletar!");
        return;
    }
    CargoJA c = listaCargos.get(linha);
    int op = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o foguete " + c.getNomeCargo() + "?", "Confirma", JOptionPane.YES_NO_OPTION);
    if (op != JOptionPane.YES_OPTION) return;

    boolean ok = CargoDAO.remover(c.getCodCargo());
    if (ok) {
        listaCargos.remove(linha);
        carregarTabelaCargos();
    }
    }//GEN-LAST:event_removerActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        carregarTabelaCargos();
    }//GEN-LAST:event_atualizarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
     if (!emEdicao) return;
    int linha = tabelaCargo.getSelectedRow();
    if (linha < 0) {
        JOptionPane.showMessageDialog(this, "Selecione a linha para salvar!");
        return;
    }

    if (!validaCampos()) return;

    CargoJA c = listaCargos.get(linha);

    c.setNomeCargo(inputNome.getText().trim());
    try {
        c.setSalarioInicial(Float.parseFloat(inputSalarioInitial.getText().trim()));
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Digite valores numéricos válidos.");
        return;
    }

    boolean ok;
    if (c.getCodCargo() == 0) {
        ok = CargoDao.inserir(c);
        if (ok) {
            inputCodigo.setText(String.valueOf(c.getCodCargo()));
        }
    } else {
        ok = CargoDao.alterar(c);
    }

    if (!ok) {
        JOptionPane.showMessageDialog(this, "Erro ao salvar/atualizar no banco.");
        return;
    }

    listaCargos = CargoDao.getLista();
    carregarTabelaCargos();
    for (int i = 0; i < listaCargos.size(); i++) {
        if (listaCargos.get(i).getCodCargo() == c.getCodCargo()) {
            tabelaCargo.setRowSelectionInterval(i, i);
            break;
        }
    }

    emEdicao = false;
    criando = false;
    trataEdicao(false);

    JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
    }//GEN-LAST:event_salvarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
    if (criando) {
        for (int i = listaCargos.size() - 1; i >= 0; i--) {
            if (listaCargos.get(i).getCodCargo() == 0) {
                listaCargos.remove(i);
                break;
            }
        }
        carregarTabelaCargos();
    } else {
        listaCargos = CargoDao.getLista();
        carregarTabelaCargos();
    }
    emEdicao = false;
    criando = false;
    trataEdicao(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FogueteJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton editar;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputSalarioInitial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remover;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tabelaCargo;
    // End of variables declaration//GEN-END:variables
}
