/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.util.List;
import javax.swing.table.DefaultTableModel;

import Script.LancamentosDAO;
import Script.LancamentosJA;
import Script.FogueteDao;
import Script.FogueteJA;
import Script.MissaoDAO;
import Script.MissaoJA;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

/**
 *
 * @author Iagod
 */
public class LancamentosJanela extends javax.swing.JFrame {

    private LancamentosDAO SensorDao = new LancamentosDAO();
    List<LancamentosJA> listaLancamentos = SensorDao.getLista();
    private FogueteDao fogueteDao = new FogueteDao();
    private MissaoDAO missaoDao = new MissaoDAO();

    private boolean emEdicao = false;
    private boolean criando = false;

    public LancamentosJanela() {
        initComponents();
    }

    LancamentosJanela(Main aThis, boolean b) {
        initComponents();
        carregarTabelaLancamentos();
        configurarComboFoguetes();
        configurarComboMissoes();
        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        inputCodigo.setEnabled(false);
        inputData.setEnabled(false);
        inputResultado.setEnabled(false);
        cbFoguetes.setEnabled(false);
        cbMissoes.setEnabled(false);
        setIconImage(new ImageIcon("src/imgs/iconeFoguete.png").getImage());
    }

    private void carregarTabelaLancamentos() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaLancamentos.getModel();
    modelo.setRowCount(0);
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    for (LancamentosJA l : listaLancamentos) {
        String dataStr = l.getDataLancamento() != null ? sdf.format(l.getDataLancamento()) : "";
        modelo.addRow(new Object[]{
            l.getCodLancamentos(),
            dataStr,
            l.getResultado(),
            l.getFogueteNome(),
            l.getMissaoNome()
        });
    }
    }

    private void configurarComboFoguetes() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        FogueteDao fdao = new FogueteDao();
        List<FogueteJA> foguetes = fdao.getLista();
        for (FogueteJA f : foguetes) {
            modelo.addElement(f);
        }
        cbFoguetes.setModel(modelo);
        cbFoguetes.setSelectedIndex(-1);
    }
    private void configurarComboMissoes() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        MissaoDAO fdao = new MissaoDAO();
        List<MissaoJA> missoes = fdao.getLista();
        for (MissaoJA f : missoes) {
            modelo.addElement(f);
        }
        cbMissoes.setModel(modelo);
        cbMissoes.setSelectedIndex(-1);
    }

    private void trataEdicao(boolean status) {
        inputData.setEnabled(status);
        inputResultado.setEnabled(status);
        cbMissoes.setEnabled(status);
        cbFoguetes.setEnabled(status);

        salvar.setEnabled(status);
        cancelar.setEnabled(status);
        cadastrar.setEnabled(!status);
        editar.setEnabled(!status);
        remover.setEnabled(!status);
        atualizar.setEnabled(!status);
    }

    public boolean validaCampos() {
        if (inputData.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a data de Lançamento");
            inputData.requestFocus();
            return false;
        }
        if (inputResultado.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o resultado do Lançamento");
            inputResultado.requestFocus();
            return false;
        }
        if (cbFoguetes.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione o foguete ao qual o lançamento pertence");
            cbFoguetes.requestFocus();
            return false;
        }
        if (cbMissoes.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione a missao ao qual o lançamento pertence");
            cbMissoes.requestFocus();
            return false;
        }
        return true;
    }

    private int gerarCodigoDisponivel() {
        int codigo = 1;
        while (true) {
            boolean existe = false;
            for (LancamentosJA s : listaLancamentos) {
                if (s.getCodLancamentos()== codigo) {
                    existe = true;
                    break;
                }
            }
            if (!existe) {
                return codigo;
            }
            codigo++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadastrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLancamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputData = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputResultado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbFoguetes = new javax.swing.JComboBox<>();
        cbMissoes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Lancamentos");

        jPanel1.setBackground(new java.awt.Color(149, 156, 182));

        cadastrar.setBackground(new java.awt.Color(37, 99, 235));
        cadastrar.setText("Criar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        editar.setBackground(new java.awt.Color(5, 150, 105));
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        remover.setBackground(new java.awt.Color(220, 38, 38));
        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        atualizar.setBackground(new java.awt.Color(245, 158, 11));
        atualizar.setText("Altualizar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        tabelaLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Data", "Resultado", "Foguete", "Missao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaLancamentos);
        if (tabelaLancamentos.getColumnModel().getColumnCount() > 0) {
            tabelaLancamentos.getColumnModel().getColumn(0).setResizable(false);
            tabelaLancamentos.getColumnModel().getColumn(1).setResizable(false);
            tabelaLancamentos.getColumnModel().getColumn(2).setResizable(false);
            tabelaLancamentos.getColumnModel().getColumn(3).setResizable(false);
            tabelaLancamentos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Codigo:");

        inputCodigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data:");

        cancelar.setBackground(new java.awt.Color(255, 0, 51));
        cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salvar.setBackground(new java.awt.Color(51, 204, 0));
        salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Resultado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Missão:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Foguete:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbFoguetes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFoguetes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cbMissoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        LancamentosJA s = new LancamentosJA();
        s.setCodLancamentos(0);
        s.setDataLancamento(null);
        s.setResultado("");
        s.setFogueteCodFoguete(0);
        s.setMissoesCodMissao(0);

        listaLancamentos.add(s);
        carregarTabelaLancamentos();

        int linha = listaLancamentos.size() - 1;
        if (linha >= 0) {
            tabelaLancamentos.setRowSelectionInterval(linha, linha);
        }

        inputCodigo.setText("0");
        inputData.setText("");
        inputResultado.setText("");
        cbFoguetes.setSelectedIndex(-1);
        cbMissoes.setSelectedIndex(-1);

        criando = true;
        emEdicao = true;
        trataEdicao(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        int linha = tabelaLancamentos.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para editar!");
            return;
        }

        LancamentosJA s = listaLancamentos.get(linha);

        inputCodigo.setText(String.valueOf(s.getCodLancamentos()));
        inputData.setText(new SimpleDateFormat("dd/MM/yyyy").format(s.getDataLancamento()));
        inputResultado.setText(s.getResultado());
        
        for (int i = 0; i < cbFoguetes.getItemCount(); i++) {
            Object obj = cbFoguetes.getModel().getElementAt(i);
            if (obj instanceof FogueteJA) {
                FogueteJA foguete = (FogueteJA) obj;
                if (foguete.getCodFoguete() == s.getFogueteCodFoguete()) {
                    cbFoguetes.setSelectedIndex(i);
                    break;
                }
            }
        }
        for (int i = 0; i < cbMissoes.getItemCount(); i++) {
            Object obj = cbMissoes.getModel().getElementAt(i);
            if (obj instanceof MissaoJA) {
                MissaoJA missao = (MissaoJA) obj;
                if (missao.getCodMissao() == s.getMissoesCodMissao()){
                    cbMissoes.setSelectedIndex(i);
                    break;
                }
            }
        }
        
        criando = false;
        emEdicao = true;
        trataEdicao(true);
    }//GEN-LAST:event_editarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
        int linha = tabelaLancamentos.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione um Lançamento para remover.");
            return;
        }

        LancamentosJA s = listaLancamentos.get(linha);

        int resposta = JOptionPane.showConfirmDialog(this,
                "Deseja realmente remover o Lançamento\"" + s.getCodLancamentos()+ "\"?",
                "Confirmação", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            LancamentosDAO dao = new LancamentosDAO();
            if (dao.remover(s.getCodLancamentos())) {
                JOptionPane.showMessageDialog(this, "Lançamento removido com sucesso!");
                listaLancamentos.remove(s);
                carregarTabelaLancamentos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao remover sensor.");
            }
        }
    }//GEN-LAST:event_removerActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        // TODO add your handling code here:
        carregarTabelaLancamentos();
    }//GEN-LAST:event_atualizarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        if (!emEdicao) {
            return;
        }

        int linha = tabelaLancamentos.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha para salvar!");
            return;
        }

        if (!validaCampos()) {
            return;
        }

        LancamentosJA s = listaLancamentos.get(linha);
        
        try {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        s.setDataLancamento(sdf.parse(inputData.getText().trim()));
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Data inválida! Use dd/MM/yyyy");
        return;
    }        
        s.setResultado(inputResultado.getText().trim());

        FogueteJA fogueteSelecionado = (FogueteJA) cbFoguetes.getSelectedItem();
        if (fogueteSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione o foguete ao qual o Lançamento pertence!");
            cbFoguetes.requestFocus();
            return;
        }
        s.setFogueteCodFoguete(fogueteSelecionado.getCodFoguete());
        
        
        MissaoJA missaoSelecionada = (MissaoJA) cbMissoes.getSelectedItem();
        if (missaoSelecionada == null) {
            JOptionPane.showMessageDialog(this, "Selecione a missao ao qual o Lançamento pertence!");
            cbMissoes.requestFocus();
            return;
        }
        s.setMissoesCodMissao(missaoSelecionada.getCodMissao());

        LancamentosDAO dao = new LancamentosDAO();
        boolean ok;

        if (s.getCodLancamentos() == 0) {
            ok = dao.inserir(s);
            if (ok) {
                inputCodigo.setText(String.valueOf(s.getCodLancamentos()));
            }
        } else {
            ok = dao.alterar(s);
        }

        if (!ok) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar/atualizar sensor no banco!");
            return;
        }

        listaLancamentos = dao.getLista();
        carregarTabelaLancamentos();

        for (int i = 0; i < listaLancamentos.size(); i++) {
            if (listaLancamentos.get(i).getCodLancamentos() == s.getCodLancamentos()) {
                tabelaLancamentos.setRowSelectionInterval(i, i);
                break;
            }
        }

        emEdicao = false;
        criando = false;
        trataEdicao(false);

        JOptionPane.showMessageDialog(this, "Sensor salvo com sucesso!");
    }//GEN-LAST:event_salvarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        emEdicao = false;
        criando = false;
        trataEdicao(false);
        carregarTabelaLancamentos();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FogueteJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FogueteJanela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> cbFoguetes;
    private javax.swing.JComboBox<String> cbMissoes;
    private javax.swing.JButton editar;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputData;
    private javax.swing.JTextField inputResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remover;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tabelaLancamentos;
    // End of variables declaration//GEN-END:variables
}
