/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Iagod
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Foguetes = new javax.swing.JMenu();
        FoguetesGerenciar = new javax.swing.JMenuItem();
        cargasGerenciar = new javax.swing.JMenuItem();
        sensoresGerenciar = new javax.swing.JMenuItem();
        abastecer = new javax.swing.JMenuItem();
        Funcionarios = new javax.swing.JMenu();
        base = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        sobre = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPACE IJP");
        setBackground(new java.awt.Color(30, 58, 95));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 156, 89));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SpaceIJP");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Verificar Condições");

        jMenuBar1.setBackground(new java.awt.Color(149, 156, 182));

        Foguetes.setText("Foguetes");
        Foguetes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        FoguetesGerenciar.setText("Gerenciar Foguetes");
        FoguetesGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoguetesGerenciarActionPerformed(evt);
            }
        });
        Foguetes.add(FoguetesGerenciar);

        cargasGerenciar.setText("Gerenciar Cargas");
        cargasGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargasGerenciarActionPerformed(evt);
            }
        });
        Foguetes.add(cargasGerenciar);

        sensoresGerenciar.setText("Gerenciar Sensores");
        Foguetes.add(sensoresGerenciar);

        abastecer.setText("Abastecer Foguetes");
        Foguetes.add(abastecer);

        jMenuBar1.add(Foguetes);

        Funcionarios.setText("Funcionarios");
        jMenuBar1.add(Funcionarios);

        base.setText("Minhas Bases");
        jMenuBar1.add(base);

        jMenu4.setText("Histórico de Lançamentos");
        jMenuBar1.add(jMenu4);

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });
        jMenuBar1.add(sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargasGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargasGerenciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargasGerenciarActionPerformed

    private void FoguetesGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoguetesGerenciarActionPerformed
        // TODO add your handling code here:
        FogueteJanela form = new FogueteJanela(this,true);
        form.setLocationRelativeTo(null); //centro na tela
        form.setResizable(false); //retira o botao maximizar
 
        form.setVisible(true); //visualizas o formulario
    }//GEN-LAST:event_FoguetesGerenciarActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sistema de Cadastro\nDireitos Reservados\nVersão: 0.1");
    }//GEN-LAST:event_sobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mains = new Main();
                mains.setLocationRelativeTo(null);
                mains.setVisible(true);
                mains.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Foguetes;
    private javax.swing.JMenuItem FoguetesGerenciar;
    private javax.swing.JMenu Funcionarios;
    private javax.swing.JMenuItem abastecer;
    private javax.swing.JMenu base;
    private javax.swing.JMenuItem cargasGerenciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem sensoresGerenciar;
    private javax.swing.JMenu sobre;
    // End of variables declaration//GEN-END:variables
}
