/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import Script.UsuarioDAO;
import Script.UsuarioJA;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.math.BigDecimal;
import javax.swing.JFrame;
import utils.BackgroundPanel;

/**
 *
 * @author Iagod
 */
public class Main extends javax.swing.JFrame {

    private UsuarioDAO usuarioDao = new UsuarioDAO();
    private UsuarioJA usuario;

    /**
     * Creates new form Main
     */
    public Main() {
        fundo = new BackgroundPanel("/imgs/estrelado.png");
        setContentPane(fundo);

        initComponents();
        setIconImage(new ImageIcon("/imgs/iconeFoguete.png").getImage());
        verifica();
    }

    private void verifica() {
        usuario = usuarioDao.localizarUsuario(1);
        if (usuario != null) {
            int valor = usuario.getPrimeiraVez();

            if (valor == 0) {
                this.setSize(1, 1);
                this.setState(JFrame.ICONIFIED);

                PrimeiraVezFrame telaBoasVindas = new PrimeiraVezFrame(this, usuario, usuarioDao);
                telaBoasVindas.setLocationRelativeTo(null);
                telaBoasVindas.setVisible(true);

                telaBoasVindas.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        usuario.setPrimeiraVez(1);
                        usuarioDao.alterar(usuario);

                        setSize(700, 500);
                        setLocationRelativeTo(null);
                        setState(JFrame.NORMAL);
                        setVisible(true);
                    }
                });
            } else {
                this.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado! Criando novo...");
            UsuarioJA novoUsuario = new UsuarioJA();
            novoUsuario.setNomeUsuario("0");
            novoUsuario.setDinheiro(BigDecimal.valueOf(200000.00));
            novoUsuario.setPrimeiraVez(0);

            usuarioDao.inserir(novoUsuario);

            JOptionPane.showMessageDialog(null, "Novo usuário criado. O aplicativo será fechado.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jToggleButton1 = new javax.swing.JToggleButton();
        fundo = new javax.swing.JPanel();
        lancar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lojinha = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Foguetes = new javax.swing.JMenu();
        FoguetesGerenciar = new javax.swing.JMenuItem();
        cargasGerenciar = new javax.swing.JMenuItem();
        sensoresGerenciar = new javax.swing.JMenuItem();
        abastecer = new javax.swing.JMenuItem();
        Funcionarios = new javax.swing.JMenu();
        GerenciaFuncionarios = new javax.swing.JMenuItem();
        GerenciaCargos = new javax.swing.JMenuItem();
        base = new javax.swing.JMenu();
        BasesGerenciar = new javax.swing.JMenuItem();
        MissaoGerenciar = new javax.swing.JMenuItem();
        DestinosGerenciar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        LancamentosGerenciar = new javax.swing.JMenuItem();
        GerenciarFinanciamentos = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPACE IJP");
        setBackground(new java.awt.Color(30, 58, 95));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);

        fundo.setBackground(new java.awt.Color(30, 58, 95));
        fundo.setOpaque(false);

        lancar.setBackground(new java.awt.Color(175, 203, 255));
        lancar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lancar.setText("Lançar Foguete");
        lancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(175, 203, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Verificar Condições");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(138, 227, 195));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SpaceIJP");

        lojinha.setBackground(new java.awt.Color(175, 203, 255));
        lojinha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lojinha.setText("Loja");
        lojinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojinhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundoLayout = new javax.swing.GroupLayout(fundo);
        fundo.setLayout(fundoLayout);
        fundoLayout.setHorizontalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addGroup(fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lojinha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lancar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        fundoLayout.setVerticalGroup(
            fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fundoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(lancar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lojinha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(149, 156, 182));

        Foguetes.setText("Foguetes");
        Foguetes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        FoguetesGerenciar.setText("Gerenciar Foguetes");
        FoguetesGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoguetesGerenciarActionPerformed(evt);
            }
        });
        Foguetes.add(FoguetesGerenciar);

        cargasGerenciar.setText("Gerenciar Cargas");
        cargasGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargasGerenciarActionPerformed(evt);
            }
        });
        Foguetes.add(cargasGerenciar);

        sensoresGerenciar.setText("Gerenciar Sensores");
        sensoresGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sensoresGerenciarActionPerformed(evt);
            }
        });
        Foguetes.add(sensoresGerenciar);

        abastecer.setText("Abastecer Foguetes");
        Foguetes.add(abastecer);

        jMenuBar1.add(Foguetes);

        Funcionarios.setText("Funcionarios");

        GerenciaFuncionarios.setText("Gerenciar Funcionários");
        GerenciaFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciaFuncionariosActionPerformed(evt);
            }
        });
        Funcionarios.add(GerenciaFuncionarios);

        GerenciaCargos.setText("Gerenciar Cargos");
        GerenciaCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciaCargosActionPerformed(evt);
            }
        });
        Funcionarios.add(GerenciaCargos);

        jMenuBar1.add(Funcionarios);

        base.setText("Minhas Bases");

        BasesGerenciar.setText("Gerenciar Bases");
        BasesGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasesGerenciarActionPerformed(evt);
            }
        });
        base.add(BasesGerenciar);

        MissaoGerenciar.setText("Gerenciar Missoes");
        MissaoGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MissaoGerenciarActionPerformed(evt);
            }
        });
        base.add(MissaoGerenciar);

        DestinosGerenciar.setText("Gerenciar Destinos");
        DestinosGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinosGerenciarActionPerformed(evt);
            }
        });
        base.add(DestinosGerenciar);

        jMenuBar1.add(base);

        jMenu4.setText("Históricos");

        LancamentosGerenciar.setText("Lançamentos");
        LancamentosGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancamentosGerenciarActionPerformed(evt);
            }
        });
        jMenu4.add(LancamentosGerenciar);

        GerenciarFinanciamentos.setText("Financiamentos");
        GerenciarFinanciamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciarFinanciamentosActionPerformed(evt);
            }
        });
        jMenu4.add(GerenciarFinanciamentos);

        jMenuBar1.add(jMenu4);

        sobre.setText("Sobre");
        sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Versão 0.1");
        sobre.add(jMenuItem2);

        jMenuBar1.add(sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargasGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargasGerenciarActionPerformed
        // TODO add your handling code here:
        CargaJanela form = new CargaJanela(this, true);
        form.setLocationRelativeTo(null); //centro na tela
        form.setResizable(false); //retira o botao maximizar

        form.setVisible(true);
    }//GEN-LAST:event_cargasGerenciarActionPerformed

    private void FoguetesGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoguetesGerenciarActionPerformed
        // TODO add your handling code here:
        FogueteJanela form = new FogueteJanela(this, true);
        form.setLocationRelativeTo(null); //centro na tela
        form.setResizable(false); //retira o botao maximizar

        form.setVisible(true); //visualizas o formulario
    }//GEN-LAST:event_FoguetesGerenciarActionPerformed

    private void sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Sistema de Cadastro\nDireitos Reservados\nVersão: 0.1");
    }//GEN-LAST:event_sobreActionPerformed

    private void sensoresGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sensoresGerenciarActionPerformed
        // TODO add your handling code here:
        SensorJanela form = new SensorJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_sensoresGerenciarActionPerformed

    private void GerenciaCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciaCargosActionPerformed
        // TODO add your handling code here:
        CargoJanela form = new CargoJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_GerenciaCargosActionPerformed

    private void GerenciaFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciaFuncionariosActionPerformed
        // TODO add your handling code here:
        FuncionarioJanela form = new FuncionarioJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_GerenciaFuncionariosActionPerformed

    private void lancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancarActionPerformed
        // TODO add your handling code here:
        SimuladorJanela form = new SimuladorJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_lancarActionPerformed

    private void BasesGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasesGerenciarActionPerformed
        // TODO add your handling code here:
        BaseJanela form = new BaseJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_BasesGerenciarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DestinosGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinosGerenciarActionPerformed
        // TODO add your handling code here:
        DestinoJanela form = new DestinoJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_DestinosGerenciarActionPerformed

    private void MissaoGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MissaoGerenciarActionPerformed
        // TODO add your handling code here:
        MissaoJanela form = new MissaoJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_MissaoGerenciarActionPerformed

    private void LancamentosGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LancamentosGerenciarActionPerformed
        // TODO add your handling code here:
        LancamentosJanela form = new LancamentosJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_LancamentosGerenciarActionPerformed

    private void GerenciarFinanciamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciarFinanciamentosActionPerformed
        // TODO add your handling code here:
        FinanciamentosJanela form = new FinanciamentosJanela(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_GerenciarFinanciamentosActionPerformed

    private void lojinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojinhaActionPerformed
        // TODO add your handling code here:
        JanelaLoja form = new JanelaLoja(this, true);
        form.setLocationRelativeTo(null);
        form.setResizable(false);

        form.setVisible(true);
    }//GEN-LAST:event_lojinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main mains = new Main();
                mains.setLocationRelativeTo(null);
                mains.setVisible(true);
                mains.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BasesGerenciar;
    private javax.swing.JMenuItem DestinosGerenciar;
    private javax.swing.JMenu Foguetes;
    private javax.swing.JMenuItem FoguetesGerenciar;
    private javax.swing.JMenu Funcionarios;
    private javax.swing.JMenuItem GerenciaCargos;
    private javax.swing.JMenuItem GerenciaFuncionarios;
    private javax.swing.JMenuItem GerenciarFinanciamentos;
    private javax.swing.JMenuItem LancamentosGerenciar;
    private javax.swing.JMenuItem MissaoGerenciar;
    private javax.swing.JMenuItem abastecer;
    private javax.swing.JMenu base;
    private javax.swing.JMenuItem cargasGerenciar;
    private javax.swing.JPanel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton lancar;
    private javax.swing.JButton lojinha;
    private javax.swing.JMenuItem sensoresGerenciar;
    private javax.swing.JMenu sobre;
    // End of variables declaration//GEN-END:variables
}
